INSERT INTO productos (nombre, precio, create_at) VALUES ('Televisor LG', 1200, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Laptop HP', 1000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('iPhone 13', 1300, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Samsung Galaxy S22', 1100, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Sony PlayStation 5', 500, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('MacBook Air', 1500, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Smartwatch Apple Watch', 400, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Cámara Canon', 600, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Auriculares Bose', 250, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Tablet Samsung', 300, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Nintendo Switch', 350, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Impresora Epson', 200, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Aspiradora Dyson', 450, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Altavoces Sonos', 150, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Raspberry Pi 4', 100, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Drone DJI', 800, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('GoPro Hero 10', 700, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Bicicleta de montaña', 600, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Horno eléctrico', 350, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Silla de oficina ergonómica', 200, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Lavadora Samsung', 800, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Cafetera Nespresso', 150, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Mochila North Face', 120, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Teclado mecánico Razer', 100, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Cepillo de dientes eléctrico Oral-B', 80, NOW());
